### ISSUE TITLE
Cannot use assetdownload

### ISSUE THREAD

**Issue by BouOus** [makehumancommunity/community-plugins-assetdownload#23] opened 2019-04-30 14:35 UTC
Help please !
I got this error : 

Importing plugin 8_asset_downloader
Imported plugin 8_asset_downloader
Loading plugin 8_asset_downloader
Could not load 8_asset_downloader
Traceback (most recent call last):
  File "./core/mhmain.py", line 580, in loadPlugin
    module.load(self)
  File "/makehuman/makehuman/plugins/8_asset_downloader/__init__.py", line 38, in load
    downloadView = category.addTask(AssetDownloadTaskView(category))
  File "/makehuman/makehuman/plugins/8_asset_downloader/assetdownload.py", line 72, in __init__
    self.assetdb = AssetDB(self)
  File "/makehuman/makehuman/plugins/8_asset_downloader/assetdb.py", line 67, in __init__
    self._loadRemoteDB()
  File "/makehuman/makehuman/plugins/8_asset_downloader/assetdb.py", line 100, in _loadRemoteDB
    asset = RemoteAsset(self,rawAsset,assetdb=self)
  File "/makehuman/makehuman/plugins/8_asset_downloader/remoteasset.py", line 75, in __init__
    self._parseMaterials()
  File "/makehuman/makehuman/plugins/8_asset_downloader/remoteasset.py", line 147, in _parseMaterials
    targetAsset = self.assetdb.assetsById[self.belongs_to_metadata["belongs_to_id"]]
KeyError: 390

**Comment by joepal1976** [comment] 2019-04-30 16:16
Which version is this? The current github master, or the one bundled with alpha 3?

**Comment by ghost** [comment] 2019-04-30 16:22
It's the current github master version.

**Comment by joepal1976** [comment] 2019-04-30 16:22
Should be fixed in current master now.

**Comment by ghost** [comment] 2019-04-30 16:31
Sorry, i make changes but same problem : 

  File "/makehuman/makehuman/plugins/8_asset_downloader/remoteasset.py", line 147, in _parseMaterials
    targetAsset = self.assetdb.assetsById[self.belongs_to_metadata["belongs_to_id"]]
KeyError: 1104

**Comment by joepal1976** [comment] 2019-05-03 04:55
Ok, I'll have to take a closer look at it. 

It was a different error message than the first time though. In the initial report it was asset 390, in the last it is 1104.

**Comment by joepal1976** [comment] 2019-05-04 08:31
I'm unable to reproduce this error. Maybe you have an inconsistent asset db locally?

Can you try to first hit synchronize and then restart makehuman to see if the problem goes away?

If it does not, can you try deleting both local.json and remote.json under data/community-assets, restart makehuman and then do synchronize?

**Comment by ghost** [comment] 2019-05-06 08:29
I did everything, but it did not change anything. I deleted the contents of the community-assets folder and restarted with syncronization and got this message again in the terminal : 

  File "/makehuman/makehuman/plugins/8_asset_downloader/remoteasset.py", line 147, in _parseMaterials
    targetAsset = self.assetdb.assetsById[self.belongs_to_metadata["belongs_to_id"]]
KeyError: 1039

**Comment by joepal1976** [comment] 2019-05-06 14:05
What confuses me is that it is different keys in each report. Within all reason, it should choke on the same asset.

Which version of makehuman are you running?

**Comment by Aranuvir** [comment] 2019-12-29 14:41
There hasn't been an update for >6 month. Closing...

**Closed by Aranuvir** 2019-12-29 14:41 UTC
Labels: bug
